version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test --single-run --no-progress --browser=ChromeHeadlessCI
      - run: npm run e2e --no-progress --config=protractor-ci.conf.js
  deployment:
    docker:
      - image: buildpack-deps:trusty
    setps:
      - checkout
      - run:
        name: Deplay master to heroku
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build_and_test:
    jobs:
      -build
      -deploy:
        requires:
          -build
          filters:
            branches:
              only: master